### ISSUE TITLE
Obtuse runtime panic when Vulkan is not installed

### ISSUE THREAD

**Issue by Zarathustra30** [tomaka/vulkano#15]
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "The specified module could not be found. (os error 126)"', ../src/libcore\result.rs:688
Process didn't exit successfully: `target\debug\vulkano-test.exe` (exit code: 101)
```

This error message could be a little clearer, such as "Vulcan not installed".

This is totally to help end users and not idiotic coders who may or may not have forgot to check whether Vulkan was actually supported on his system.

**Comment by tyoc213** [comment]
@tomaka today on a new win computer I got that

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LoadingError(LibraryLoadFailure("El modulo especificado no se encuentra (os error 126)"))', src\libcore\result.rs:860:4
```

I can send a PR with basically this

```diff
diff --git a/vulkano/src/instance/instance.rs b/vulkano/src/instance/instance.rs
index 6550e52b..5af8ca6a 100644
--- a/vulkano/src/instance/instance.rs
+++ b/vulkano/src/instance/instance.rs
@@ -132,8 +132,13 @@ impl Instance {
             .map(|&layer| CString::new(layer).unwrap())
             .collect::<SmallVec<[_; 16]>>();
 
+        let vulkan_lib_fps = loader::auto_loader();
+        if vulkan_lib_fps.is_err() {
+            eprintln!("See http://vulkano.rs/troubleshooting#install_vulkan");
+        }
+        let vulkan_lib_fps = vulkan_lib_fps?;
         Instance::new_inner(app_infos, extensions.into(), layers,
-                            OwnedOrRef::Ref(loader::auto_loader()?))
+                            OwnedOrRef::Ref(vulkan_lib_fps))
     }
 
     /// Same as `new`, but allows specifying a loader where to load Vulkan from.

```

In any case I dont know how it didnt show `failed to load the Vulkan shared library`

**Comment by tomaka** [comment]
I'm in favor of making the error better, but I don't think a library should ever print on stdout/stderr.
