### ISSUE TITLE
Resizing window: 'unexpected error: DeviceLost'

### ISSUE THREAD

**Issue by skligys** [tomaka/vulkano#366]
I am trying to implement window resizing by following the sample code at [https://docs.rs/vulkano/0.3.1/vulkano/swapchain/index.html#recreating-a-swapchain](documentation), unsuccessfully.

Here is a simple modification to the triangle example I tried: [commit](https://github.com/skligys/vulkano/commit/416c761df39dd70ebac4d728d037cf06ad7755be).

I run on Arch Linux with Nvidia driver v375.26.  On resize, I see the process hogging 100% CPU for ~15 seconds, FPS printouts stop, then it crashes.  Any ideas what I am doing wrong?

```
$ cargo build && RUST_BACKTRACE=1 ../target/debug/triangle 
warning: cpp_set_stdlib is specified, but the Gnu compiler does not support this option, ignored
   Compiling examples v0.1.0 (file:///home/skirmis/Temp/vulkano/examples)
    Finished debug [unoptimized + debuginfo] target(s) in 5.26 secs
Using device: GTX 750 Ti (type: DiscreteGpu)
----- Event Resized(796, 1196)
FPS: 2011.6
FPS: 2100.7
FPS: 2115.7
FPS: 2113.4
FPS: 2000.1
FPS: 2022.4
----- Event Resized(796, 1179)
>>>>> Recreate swapchain with dimensions (796, 1179)
<<<<< Recreate swapchain with dimensions (796, 1179)
----- Event Resized(796, 1196)
FPS: 61.2
>>>>> Recreate swapchain with dimensions (796, 1196)
<<<<< Recreate swapchain with dimensions (796, 1196)
FPS: 59.1
thread 'main' panicked at 'unexpected error: DeviceLost', /home/skirmis/Temp/vulkano/vulkano/src/lib.rs:151
stack backtrace:
   1:     0x5598268eea3c - std::sys::imp::backtrace::tracing::imp::write::h2a972e172776bc73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5598268f0fde - std::panicking::default_hook::{{closure}}::h3350be9abe4c8496
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5598268f0be4 - std::panicking::default_hook::h255964940ef72e84
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x5598268f1487 - std::panicking::rust_panic_with_hook::ha02a85ff57cdb669
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5598268f12c4 - std::panicking::begin_panic::h3472a76248a19370
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5598268f1239 - std::panicking::begin_panic_fmt::h353221386e3766a5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55982672f27b - <vulkano::OomError as core::convert::From<vulkano::Error>>::from::hdafa6a42b8d0928d
                        at /home/skirmis/Temp/vulkano/examples/<panic macros>:8
   8:     0x5598266b3aea - <vulkano::sync::fence::Fence<D>>::ready::ha74003902015a3d8
                        at /home/skirmis/Temp/vulkano/examples/<try macros>:6
   9:     0x559826734739 - vulkano::command_buffer::inner::Submission::finished::h90661d9d840bb060
                        at /home/skirmis/Temp/vulkano/vulkano/src/command_buffer/inner.rs:2095
  10:     0x55982673464c - vulkano::command_buffer::inner::Submission::destroying_would_block::h40b8771bd3ea06ff
                        at /home/skirmis/Temp/vulkano/vulkano/src/command_buffer/inner.rs:2089
  11:     0x55982676033d - triangle::main::{{closure}}::h28239630505198cb
                        at /home/skirmis/Temp/vulkano/examples/src/bin/triangle.rs:406
  12:     0x5598266a235b - <collections::vec::Vec<T>>::retain::h4e9a7cd363228a59
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:802
  13:     0x55982675ecd4 - triangle::main::h845c4b617f32f93f
                        at /home/skirmis/Temp/vulkano/examples/src/bin/triangle.rs:406
  14:     0x5598268f7f0a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x5598268f1986 - std::rt::lang_start::h836f853bc2506201
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  16:     0x559826765272 - main
  17:     0x7fbd13713290 - __libc_start_main
  18:     0x559826668529 - _start
  19:                0x0 - <unknown>
```

**Comment by tomaka** [comment]
The "crash" is caused by a device lost, which means that the GPU likely took too much time or had a problem while processing a command buffer.

If I had to guess, it's maybe vulkano's internals that ask to wait on a semaphore that is never signalled.

I'm not going to deep down into this, as this part of the code is being totally reworked in the `incoming` branch.

**Comment by skligys** [comment]
Pierre,

Thanks for taking a look.  I tried the same approach on top of incoming branch, and it works just fine there.

I will just use the incoming branch then.  This is a personal project to learn Vulkan, so unstable base is fine as long as I can find some commit that works for my simple needs.

Do you plan to merge incoming into master any time soon?

**Comment by tomaka** [comment]
> Do you plan to merge incoming into master any time soon?

Soon, no. There's still an aspect whose design is blurry.
