### ISSUE TITLE
Creating an empty CpuAccessibleBuffer assertion fail

### ISSUE THREAD

**Issue by rukai** [tomaka/vulkano#367]
```
extern crate vulkano;

use vulkano::instance::{Instance, InstanceExtensions};
use vulkano::buffer::{CpuAccessibleBuffer, BufferUsage};
use vulkano::device::{Device, DeviceExtensions};

fn main() {
    let instance = Instance::new(None, &InstanceExtensions::none(), None).unwrap();
    let physical = vulkano::instance::PhysicalDevice::enumerate(&instance).next().unwrap();
    let queue = physical.queue_families().find(|q| { q.supports_graphics() }).unwrap();

    let (device, mut queues) = Device::new(&physical, physical.supported_features(),
        &DeviceExtensions::none(), [(queue, 0.5)].iter().cloned()).unwrap();
    let queue = queues.next().unwrap();

    let indices: Vec<u16> = vec!();
    CpuAccessibleBuffer::from_iter(&device, &BufferUsage::all(), Some(queue.family()), indices.iter().cloned()).unwrap();
}
```
I have no idea if the panic here is supposed to happen?
But if it is, it should have a more descriptive error message.
The current message is: 
```
thread 'main' panicked at 'assertion failed: size != 0', /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/memory/pool/host_visible.rs:63
stack backtrace:
   1:     0x55e7eb90862c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55e7eb90a58e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55e7eb90a194 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55e7eb90a9cb - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55e7eb8ce183 - std::panicking::begin_panic::h5f56646f8d8764e1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55e7eb8edd0f - vulkano::memory::pool::host_visible::StdHostVisibleMemoryTypePool::alloc::h2a29b623bb66d835
                        at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/memory/pool/host_visible.rs:63
   7:     0x55e7eb8f0f43 - vulkano::memory::pool::pool::<impl vulkano::memory::pool::MemoryPool for alloc::arc::Arc<vulkano::memory::pool::pool::StdMemoryPool>>::alloc::h4fbb0bdc121c5cb7
                        at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/memory/pool/pool.rs:81
   8:     0x55e7eb8ad1db - <vulkano::buffer::cpu_access::CpuAccessibleBuffer<T>>::raw::hfa191af718fb8322
                        at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/buffer/cpu_access.rs:227
   9:     0x55e7eb8bc1fe - <vulkano::buffer::cpu_access::CpuAccessibleBuffer<[T]>>::uninitialized_array::hae3e05d2d2788d41
                        at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/buffer/cpu_access.rs:189
  10:     0x55e7eb8bc39d - <vulkano::buffer::cpu_access::CpuAccessibleBuffer<[T]>>::from_iter::h56f2c877364cb75c
                        at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.3.1/src/buffer/cpu_access.rs:150
  11:     0x55e7eb8c2fda - vulkan_test::main::h204f5ff4655738e0
                        at /home/rubic/Foo/vulkan_test/src/main.rs:17
  12:     0x55e7eb9112aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  13:     0x55e7eb90aed6 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  14:     0x55e7eb8c31b2 - main
  15:     0x7ffa638d0290 - __libc_start_main
  16:     0x55e7eb88f009 - _start
  17:                0x0 - <unknown>
```

**Comment by tomaka** [comment]
The panic is caused by the fact that you're trying to create a buffer with zero element in it.

I agree that it shouldn't be a panic but an error instead.
