### ISSUE TITLE
Weird problems with examples 

### ISSUE THREAD

**Issue by fst3a** [tomaka/vulkano#476]
Hello

I have tried running examples and ran into certain problems.  When running on GNU/Linux with Wayland windowing, examples get stuck on
```
events_loop.poll_events(|ev| {
    match ev {
        winit::Event::WindowEvent { event: winit::WindowEvent::Closed, .. } => done = true,
        _ => ()
    }
});
```
at the end of iteration.  For some reason `poll_events` get stuck and doesn't run anything.  It's likely a winit related issue.  Removing `poll_events` call solves the issue and program is unstuck but then there's no way to get events.

When running on GNU/Linux with X11 windowing, example will play few frames and then get stuck at `let (image_num, acquire_future) = swapchain.acquire_next_image(Duration::new(1, 0)).unwrap();` and eventually panic.  Backtrace from teapot.rs example:
```
examples% RUST_BACKTRACE=1 cargo run --bin teapot
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/tmp/vulkano/target/debug/teapot`
Using device: Intel(R) HD Graphics 520 (Skylake GT2) (type: IntegratedGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: teapot::main
             at src/bin/teapot.rs:182
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:56
  14: main
  15: __libc_start_main
  16: _start
```
When running on (other system) with Windows 10 with AMD R7 M265 all examples seem to work fine.

Used rustc 1.17.0 (56124baa9 2017-04-24).  Here's [vulkaninfo](https://github.com/tomaka/vulkano/files/1027398/vulkaninfo.txt) of HD Graphics 520 system.

**Comment by tomaka** [comment]
> example will play few frames and then get stuck at let (image_num, acquire_future) = swapchain.acquire_next_image(Duration::new(1, 0)).unwrap(); and eventually panic.

That's a known issue with Mesa (#387).

**Comment by fst3a** [comment]
I see, thanks.

**Comment by fst3a** [comment]
Hm, apparently winit part now works fine with upstream winit (straight from github).
