### ISSUE TITLE
Panic on teapot example with Intel(R) HD Graphics 530

### ISSUE THREAD

**Issue by JohnDoneth** [tomaka/vulkano#523]
When running the teapot example on Windows 8.1 with Intel Graphics Driver version 21.20.16.4678 (Most Recent), or 20.19.15.4404 (Vulkan Specific Drivers), the following error message occurs:

```
Using device: GPU (type: IntegratedGpu)
thread 'main' panicked at 'explicit panic', C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\command_buffer\cb\submit_sync.rs:794
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<&str>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: vulkano::command_buffer::cb::submit_sync::{{impl}}::prepare_submit<vulkano::command_buffer::cb::abstract_storage::AbstractStorageLayer<vulkano::command_buffer::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulka
no::command_buffer::pool::standard::StandardCommandPool>>>>
             at ./<panic macros>:3
   6: vulkano::command_buffer::traits::CommandBuffer::execute_after<vulkano::command_buffer::cb::submit_sync::SubmitSyncLayer<vulkano::command_buffer::cb::abstract_storage::AbstractStorageLayer<vulkano::command_buffe
r::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>,vulkano::swapchain::swapchain::SwapchainAcquireFuture>
             at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\command_buffer\traits.rs:121
   7: vulkano::sync::future::GpuFuture::then_execute<vulkano::swapchain::swapchain::SwapchainAcquireFuture,vulkano::command_buffer::cb::submit_sync::SubmitSyncLayer<vulkano::command_buffer::cb::abstract_storage::Abst
ractStorageLayer<vulkano::command_buffer::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>>
             at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\sync\future\mod.rs:147
   8: teapot::main
             at ./src\bin\teapot.rs:196
   9: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  10: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  11: main
  12: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  13: BaseThreadInitThunk
thread 'main' panicked at 'explicit panic', C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\swapchain\swapchain.rs:544
stack backtrace:
   0:     0x7ff68d510255 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1:     0x7ff68d516cf7 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:354
   2:     0x7ff68d5165d9 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:371
   3:     0x7ff68d517251 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:549
   4:     0x7ff68d48b5ef - std::panicking::begin_panic<&str>
                               at C:\projects\rust\src\libstd\panicking.rs:511
   5:     0x7ff68d4e74a3 - vulkano::swapchain::swapchain::{{impl}}::drop
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\swapchain\swapchain.rs:544
   6:     0x7ff68d3959ba - __STATIC_FMTSTR
   7:     0x7ff68d3f4741 - vulkano::command_buffer::traits::CommandBuffer::execute_after<vulkano::command_buffer::cb::submit_sync::SubmitSyncLayer<vulkano::command_buffer::cb::abstract_storage::AbstractStorageLayer<v
ulkano::command_buffer::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>,vulkano::swapchain::swapchain::SwapchainAcquireFuture>
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\command_buffer\traits.rs:134
   8:     0x7ffde517c21f - _C_specific_handler
   9:     0x7ffde5172719 - _FrameUnwindFilter
  10:     0x7ffde51719f1 - memchr
  11:     0x7ffde517b93f - _CxxFrameHandler3
  12:     0x7ffe1240347c - _chkstk
  13:     0x7ffe123c5404 - RtlUnwindEx
  14:     0x7ffde517bd08 - FindAndUnlinkFrame
  15:     0x7ffde5172868 - _FrameUnwindFilter
  16:     0x7ffde5171f0e - memchr
  17:     0x7ffde5171aed - memchr
  18:     0x7ffde517b93f - _CxxFrameHandler3
  19:     0x7ffe124033fc - _chkstk
  20:     0x7ffe123c4846 - RtlRaiseException
  21:     0x7ffe123c3a6c - RtlRaiseException
  22:     0x7ffe0f5e95fb - RaiseException
  23:     0x7ffde5174461 - CxxThrowException
  24:     0x7ff68d517f8b - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:112
  25:     0x7ff68d517384 - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:580
  26:     0x7ff68d517313 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:565
  27:     0x7ff68d35d4bf - std::panicking::begin_panic<&str>
                               at C:\projects\rust\src\libstd\panicking.rs:511
  28:     0x7ff68d31626f - vulkano::command_buffer::cb::submit_sync::{{impl}}::prepare_submit<vulkano::command_buffer::cb::abstract_storage::AbstractStorageLayer<vulkano::command_buffer::cb::sys::UnsafeCommandBuffer<
alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\examples\<panic macros>:3
  29:     0x7ff68d3f4352 - vulkano::command_buffer::traits::CommandBuffer::execute_after<vulkano::command_buffer::cb::submit_sync::SubmitSyncLayer<vulkano::command_buffer::cb::abstract_storage::AbstractStorageLayer<v
ulkano::command_buffer::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>,vulkano::swapchain::swapchain::SwapchainAcquireFuture>
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\command_buffer\traits.rs:121
  30:     0x7ff68d3f57af - vulkano::sync::future::GpuFuture::then_execute<vulkano::swapchain::swapchain::SwapchainAcquireFuture,vulkano::command_buffer::cb::submit_sync::SubmitSyncLayer<vulkano::command_buffer::cb::a
bstract_storage::AbstractStorageLayer<vulkano::command_buffer::cb::sys::UnsafeCommandBuffer<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>>>>
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\vulkano\src\sync\future\mod.rs:147
  31:     0x7ff68d423ee8 - teapot::main
                               at C:\Users\donethjo\Desktop\GitHub\vulkano\examples\src\bin\teapot.rs:196
  32:     0x7ff68d517eb1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  33:     0x7ff68d517528 - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:51
  34:     0x7ff68d42dd2b - main
  35:     0x7ff68d522cc8 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  36:     0x7ffe103313d1 - BaseThreadInitThunk
thread panicked while panicking. aborting.
error: process didn't exit successfully: `C:\Users\donethjo\Desktop\GitHub\vulkano\target\debug\teapot.exe` (exit code: 3221225501)
```

**Comment by tomaka** [comment]
I think you git repo is not up to date. There used to be a panic at this location, but it was removed a few days/weeks ago.

**Comment by JohnDoneth** [comment]
That was indeed the issue, my version of the repository was a day or so old. After syncing the repository, and updating rustup, the example now runs. Thank you for the quick response.
